### ISSUE TITLE
Define which UI will be the final planning UI

### ISSUE THREAD

**Issue by aloysiogl** [aloysiogl/nupanca#11]
- Run tests with the different designs in figma

- Have a metting to wrap up the information collected

**Comment by asilvaigor** [comment]
Development link: [Figma](https://www.figma.com/file/SgpgxMj9hENOAm0tXUfXCX/nupanca-Copy?node-id=0%3A1)

All screens development link: [Figma](https://www.figma.com/file/8BdnovGDZaEXlKRVajRurP/nupanca---all-screens-navigation?node-id=0%3A1)

### Current: two candidates

- As of now, we have defined this page to be one of the candidates. To be defined: is showing salary really necessary?

![Gastos v2-1](https://user-images.githubusercontent.com/18221882/86545615-54b3cd00-bf06-11ea-98f6-a3ebca88d8e7.png)

- One of these 5 pages are to be chosen to be the second candidate.

![Group 7](https://user-images.githubusercontent.com/18221882/86545644-875dc580-bf06-11ea-98a5-f7b3c1031a49.png)

**Comment by aloysiogl** [comment]
Links para os protótipos:

- [Protótipo principal] - https://www.figma.com/proto/SgpgxMj9hENOAm0tXUfXCX/nupanca-(Copy)?node-id=95%3A40&scaling=scale-down
- [Telas alternativas] - https://www.figma.com/proto/8BdnovGDZaEXlKRVajRurP/nupanca---all-screens-navigation?node-id=95%3A40&scaling=scale-down

**Comment by aloysiogl** [comment]
Cards with arrow
