### ISSUE TITLE
Insert money still not as nubank app

### ISSUE THREAD

**Issue by aloysiogl** [aloysiogl/nupanca#2]
Can't change cursor location in insert money and cursor location defaults to the left, not to the right

**Comment by asilvaigor** [comment]
We could implement a behavior that works and use it in all of the inputs throughout the app

**Comment by asilvaigor** [comment]
Implemented [CurrencyOnChangeListener](https://github.com/aloysiogl/nupanca/blob/master/app/src/main/java/com/nupanca/CurrencyOnChangeListener.kt) which centralizes and fixes the currency inputs
