### ISSUE TITLE
Goals money distribution with weird behaviors

### ISSUE THREAD

**Issue by asilvaigor** [aloysiogl/nupanca#8]
Playing adding two goals with different priorities has a lot of weird behaviors:
- Sometimes when the second goal is added, its progress bar isn't updated right away, and we need to go back to the main screen and return for it to work
- Sometimes both bars will be completely empty
- Completion dates are also incorrect: sometimes it says I'll complete it in time even though the estimated time is after the deadline. Data used: {Goal1 R$2000 18/09/2020}, {Goal2 R$ 150000 05/07/2025}
- These three screenshots below are from an even weirder bug, in which one of the goals disappeared
![Screenshot from 2020-07-05 16-16-26](https://user-images.githubusercontent.com/18221882/86540369-076e3600-bedb-11ea-8c52-08000315567e.png)
![Screenshot from 2020-07-05 16-13-59](https://user-images.githubusercontent.com/18221882/86540370-0806cc80-bedb-11ea-9186-8c20429ada00.png)
![Screenshot_20200705-161455](https://user-images.githubusercontent.com/18221882/86540374-17861580-bedb-11ea-9c73-c07f4c61340e.jpg)

**Comment by aloysiogl** [comment]
- [x] Not updating predictions when returning from deletion to the goal list screen
- [x] Not updating predictions when returning from edit to goal show screen
